NASAQ/NASAQ/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth
from django.urls import path, include
from apps.usuarios import views as v
from apps.categorias import views as c
from . import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name= 'home'),
    path('nosotros/', views.Nosotros, name= 'nosotros'),
    path('login/', auth.LoginView.as_view(template_name = 'usuarios/login.html'), name= 'login'),
    path('logout/', auth.LogoutView.as_view(), name = 'logout'),
    path('registro/', v.Registro, name='registro'),
    path('juego/', views.Juego, name='juego'),
    path('nasacos/', include('apps.categorias.urls')),
    path('partida/', include('apps.juego.urls')),
]

NASAQ/apps/categorias/urls.py
from django.urls import path, include
from .import views


app_name = 'categorias'

urlpatterns = [
	path('categorias/', views.ListarCategorias, name = 'categorias'),
	
]

NASAQ/apps/juego/urls.py
from django.urls import path, include
from .import views


app_name = 'juego'

urlpatterns = [
	path('jugar/<int:pk>', views.Jugar, name = 'jugar'),
	path('respuesta/<int:pk>', views.Responder, name = 'respuesta'),
	path('siguiente/<int:pk>', views.Siguiente, name = 'siguiente'),
	path('ranking/', views.Ranking, name = 'ranking'),

]

NASAQ/apps/categorias/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
	nombre = models.CharField(max_length = 50)
	
	def __str__(self):
		return self.nombre

NASAQ/apps/core/models.py
from django.db import models

# Create your models here.
class TimeModel(models.Model):
  creado = models.DateTimeField(auto_now_add=True,
                                  verbose_name=u'creado',
                                  help_text=u'Fecha de creación')
  modificado = models.DateTimeField(auto_now=True,
                                      verbose_name=u'modificado',
                                      help_text=u'Fecha de modificación')

  class Meta:
    abstract = True
  

NASAQ/apps/juego/models.py
from django.db import models
from apps.categorias.models import Categoria
from apps.usuarios.models import Usuario

# Create your models here.

class Partida(models.Model):
	usuario = models.ForeignKey(Usuario, on_delete = models.CASCADE)
	categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE)
	puntaje = models.IntegerField(default = 0)
	pregunta_actual = models.IntegerField(default = 0)
	
	
	
	


	

NASAQ/apps/pregresp/models.py
from django.db import models
from apps.categorias.models import Categoria

# Create your models here.

class PregYResp(models.Model):
	pregunta = models.CharField(max_length = 200)
	respuesta1 = models.CharField(max_length = 200)
	respuesta2 = models.CharField(max_length = 200)
	respuesta3 = models.CharField(max_length = 200)
	respuesta_correcta = models.CharField(max_length=200)
	puntaje = models.IntegerField(default = 0)
	categoria = models.ForeignKey(Categoria, related_name= 'mi_categoria', on_delete = models.CASCADE , null = True)


	def __str__(self):
		return self.pregunta

	def getPuntaje(self):
		return self.puntaje

NASAQ/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class Usuario(AbstractUser):
	pass

NASAQ/apps/usuarios/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()
class RegistroFormulario(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User 
		fields = ['username', 'email', 'password1', 'password2']

NASAQ/NASAQ/views.py
from django.shortcuts import render


def Home(request):
	return render(request, 'home.html')

def Nosotros(request):
	return render(request, 'nosotros.html')

def Login(request):
	return render(request, 'usuarios/login.html')

def Registro(request):

	return render(request, 'usuarios/registro.html')

def Juego(request):
	return render(request, 'juego/nasac.html')

NASAQ/apps/categorias/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Categoria




# Create your views here.

@login_required
def ListarCategorias(request):
	context = {}
	# BUSCAR TODOS LOS CATEGORIAS DE LA BD
	#Categorias.objects.all() SE TRANFORMA EN:
	# SELECT * FROM Categorias
	todas = Categoria.objects.all() #ORM DE DJANGO
	# PASARLOS AL TEMPLATE

	context['categorias'] = todas # ESTO ES UNA LISTA DE OBJETOS
	
	return render(request,'juego/categoriaJuego.html',context)

NASAQ/apps/core/views.py
from django.shortcuts import render

# Create your views here.

NASAQ/apps/juego/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from apps.categorias.models import Categoria
from apps.pregresp.models import PregYResp
from .models import Partida

# Create your views here.

@login_required
def Jugar(request, pk):
	context = {}
	objeto = Categoria.objects.get(id = pk)
	
	p = Partida.objects.create(usuario=request.user, categoria=objeto)
	g= PregYResp.objects.filter(categoria = objeto)[0]
	context['preguntas'] = g
	context['juego'] = p
	return render(request,'juego/preguntas.html',context)

@login_required
def Responder(request, pk):
	context = {}
	objeto = Partida.objects.get(id = pk)
	pregunta = PregYResp.objects.get(id = request.POST.get("id_pregunta"))

	respuesta = None
	for i in request.POST:
		if i != 'csrfmiddlewaretoken' and i != 'id_pregunta':
			respuesta=i 

	if respuesta==pregunta.respuesta_correcta:
		mensaje="Respuesta correcta! Adelante!!!"
		objeto.puntaje+=10
	else:
		mensaje="Respuesta incorrecta! Siga participando!!!"
	
	context['mensaje']=mensaje

	objeto.pregunta_actual+=1
	objeto.save()
	context['juego']=objeto
	return render(request,'juego/resultado.html',context)

@login_required
def Siguiente(request, pk):
	context = {}
	objeto = Partida.objects.get(id = pk)
	actual=objeto.pregunta_actual
	if actual < 7:
		g= PregYResp.objects.filter(categoria = objeto.categoria)[actual]
		context['preguntas'] = g
		context['juego'] = objeto
	else:
		context['juego']=objeto
		return render(request, 'juego/final.html',context)

	return render(request,'juego/preguntas.html',context)

@login_required
def Ranking(request):
	context={}
	ranking = Partida.objects.all().order_by('-puntaje')[:10]

	context['ranking']=ranking
	return render(request, 'juego/ranking.html',context)

NASAQ/apps/pregresp/views.py
# Create your views here.

NASAQ/apps/usuarios/views.py
from django.shortcuts import render
from .forms import RegistroFormulario


# Create your views here.

def Registro(response):
	if response.method == 'POST':
		form = RegistroFormulario (response.POST)
		if form.is_valid():
			form.save()

	else:
		form = RegistroFormulario()

	return render(response, 'usuarios/registro.html', {'form' : form})

NASAQ/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>N A S A C</title>
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/principal.css' %}"> 
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}">
 
  </head>


 <body>
    <header>
     
      <nav>
        <ul>
            
            <li><a href="{% url 'home' %}"><h2>INCIO</h2></a></li>
            <li><a href="{% url 'nosotros' %}"><h2>NOSOTROS</h2></a></li>

            {% if user.is_authenticated %}
                <li><a href="{% url 'juego' %}"><h2>JUEGO</h2></a></li>
                
                <li><img src="{% static 'img/favicon3.png' %}" alt="logo NASAC" width="80%" align="center"></li>
                <li>      </li>
                <li><a href="{% url 'home' %}"><h2>{{user.username}}</h2></a></li>
                <li><a href="{% url 'logout' %}"><h2>SALIR</h2></a></li>
            {% else %}
                <li><a href="{% url 'login' %}"><h2>JUEGO</h2></a></li>
                
                <li><img src="{% static 'img/favicon3.png' %}" alt="logo NASAC" width="80%" align="center"></li>
                <li>      </li>
                <li><a href="{% url 'login' %}"><h2>ENTRAR</h2></a></li>
                <li><a href="{% url 'registro' %}"><h2>REGISTRO</h2></a></li>
            {% endif %}
        </ul>
      </nav>
    </header>

   
        <div>
              {% block contenido %}
  
              {% endblock contenido %} 
        </div>
       
      
  </body>

</html>

NASAQ/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}
	<br><br><br><br>
	<center><p>
        <h2 class= "parrafo">
          En el año 2021, en el curso INFORMATORIO, sobre programación web; se desarrolla el juego NASAC <br>
          (lengua de origen QOM, cuyo significado invita a jugar; con la implicancia que tiene en el <br>70 aniversario de la creación del Chaco, a modo de aporte o una forma más de reconocimiento <br>a nuestros hermanos originarios de este suelo). <br> En esta página se pondrá a prueba su conocimiento sobre la provincia a través del juego, <br> de manera lúdica siendo una invitación a conocer algo más sobre nuestras raices,<br> culturales y antonomásicas que nos dan identidad como pueblo CHAQUEÑO!<br>
          <br>Para jugar simplemente REGÍSTRESE, luego avance en el juego y el conocimiento de nuestro terruño.  
        </h2>  
    </p></center>
{% endblock contenido %}

NASAQ/templates/juego/categoriaJuego.html
{% extends 'base.html' %}

{% load static %}


{% block contenido %}
	
	<center><h1>CATEGORIAS</h1></center>
	
	{% for p in categorias %}
		<center>
			<a href="{% url 'juego:jugar' p.id %}"><h2>{{p.nombre}}</h2></a>
			<p>______________________</p></center>
	{% endfor %}

{% endblock contenido %}

NASAQ/templates/juego/final.html
{% extends 'base.html' %}
{% load static %}
	

{% block contenido %}
	<center><div>
		<h2>Tu puntaje final es: {{juego.puntaje}}</h2>
		<a href="{% url 'juego:ranking' %}"> 
		<button type="submit" class="button"> 
			RANKING
		</button>
	</a>
	</div></center>
	
	

{% endblock contenido %}

NASAQ/templates/juego/nasac.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}
     <center><p>
           <h2 class="parrafo">
            Cuando acceda al botón inferior 'NASAC', encotrará una serie de trivias, definida por categorías, <br>
            en total de 7. Cada una de ellas cuenta con 7 consignas y 3 respuestas probables.<br>ATENTO! <br>Solo una de ellas es la opción correcta, recorre las 7 preguntas de la categoría!<br> Cada consigna suma 10 puntos, valore su conocimiento sumando correctas y espíe el ranking final!<br><br>  Total máximo posible, por partida = 70 puntos.<br><br>      Total de años de nuestra provincia = 70 años.<br><br>          Vamos por más! <br><br>ÉXITOS!
          </h2>    
        </p></center>
        
         <center><a href="{% url 'categorias:categorias' %}"><button type="submit"class="button">NASAC</button></a></center>

        
{% endblock contenido %}




             


      	
    

NASAQ/templates/juego/preguntas.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}
<center><h1 class="parrafo">{{preguntas.pregunta}}</h1><br><br>
	<form method="POST" action="{% url 'juego:respuesta' juego.id %}"> {% csrf_token %}
		<h3 class="parrafo"><label><input type="checkbox" name="{{preguntas.respuesta1}}" value="{{preguntas.respuesta1}}">{{preguntas.respuesta1}}</label></h3><br>

		<h3 class="parrafo"><label><input type="checkbox" name="{{preguntas.respuesta2}}" value="{{preguntas.respuesta2}}">{{preguntas.respuesta2}}</label></h3><br>

		<h3 class="parrafo"><label><input type="checkbox" name="{{preguntas.respuesta3}}" value="{{preguntas.respuesta3}}">{{preguntas.respuesta3}}</label></h3><br>
	
		<button type="submit" class="button">enviar</button>
		<input type="text" name="id_pregunta" value="{{preguntas.id}}" hidden="">
	</form>
</center>

{% endblock contenido %}

 

NASAQ/templates/juego/ranking.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}
	<center><div>
		<h1 class="text-center my-4"> 
		<span class="badge badge-info">
			Los 10 mejores jugadores NASAQUISTAS!!!
		</span>
	</h1>
	<p><h2 class="parrafo">
	<table class="table table-striped table-bodered">
		<thead>
			<tr>
				<td><th>Usuario</th></td>
				<td><th>Puntaje</th></td>
			</tr>
		</thead>
		<tbody>
			{% for r in ranking %}
				<tr>
					<td></td><th>{{r.usuario}}</th></td>
					<td></td><th>{{r.puntaje}}</th>
				</tr>
			{% endfor %}
		</tbody>
	</table></h2>
	</p>
	</div></center>
	
	
{% endblock contenido %}

NASAQ/templates/juego/resultado.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}
	<center><div>
		<h1>{{mensaje}}</h1>
		<a href="{% url 'juego:siguiente' juego.id %}"> 
		<button type="submit" class="button"> 
			SIGUIENTE
		</button>
	</a>
	</div></center>
	

{% endblock contenido %}

NASAQ/templates/nosotros.html
{% extends 'base.html' %}

{% load static %}


 {% block contenido %}    
        <center>
            <br><br><h1 class="parrafo">S o m o s :</h1>
            <p> <h2 class="parrafo">
            	Un grupo de curiosos en asuntos de la PROGRAMACIÓN, y hemos sido parte del INFORMATORIO 2021.<br><br>
              Andrea MORINIGO - Resistencia.<br> 
              Facundo RETAMOZO - Villa Ángela.<br>
              Johana TITA FERREYRA -  Resistencia.<br>
              Mauro Gonzalo ROTH - Sáenz Peña.<br>
              Tatiana MIJALUK - Sáenz Peña.<br>
              Christian PERALTA - Resistencia.<br>
              Dino BARTOLONI - Sáenz Peña.<br>
              Nicolas TORTOSA - Resistencia -guía espiritual y cognitivo-.</h2>
            </p>
        
        <section class="contact" id="contact">

            <form>
                <h4 class="parrafo">Contactanos</h4>
                <div class="form-item">
                    <h5><label for="message"></label><textarea name="mensaje" id="message" cols="50" rows="10" placeholder="Dejanos tu mensaje"></textarea>
                </div>
                <div class="form-item">
                    <label for="name"> Nombre: </label><input id="name" type="text" name="name"></div>
                <div class="form-item">
                    <label for="lastName"> Apellido: </label><input id="lastName" type="text" name="lastName">
                </div>
                <div class="form-item">
                    <label for="email"> E-mail:  </label><input id="email" type="email" name="email">
                </div>

                <div class="submit-reset">
                    <input type="submit" class="button" name="submit" value="Enviar">
                    <input type="reset" class="button" name="cancel" value="Cancelar"></h5>
                </div>
            </form>
        </section>             
        </center>
              {% endblock contenido %} 
     

NASAQ/templates/usuarios/login.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
	<br><br><br><br><br>
	
	<div>
		<form method="POST"> {% csrf_token %}
			{{form.errors}}
			<center><input type="text" name="username" placeholder="USUARIO"></center> <br>
			<center><input type="password" name="password" placeholder="CONTRASEÑA"></center> <br>

			<center><input type="submit" name="" value="LOGIN"></center>
			<center><a href="{% url 'registro' %}" class="regLogin"><h3>Crear Usuario</h3></a></center>
		</form>
	</div>
	
{% endblock contenido %}

NASAQ/templates/usuarios/registro.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Creando una Cuenta{% endblock %}
{% load crispy_forms_tags %}
{% block contenido %}
	<h1>Registro</h1>

	<form method="POST" class="form-group">{% csrf_token %}
	  <center>{{form.errors}}</center>
	  <center>{{ form|crispy }}</center>
	  <center><input type="submit" class="btn btn-success" name="enviar" value="Guardar"></center>
	</form>

		
		
{% endblock contenido %}